[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]
  included_files = ["netlify/functions/_lib/users_fixed.json"]
